config/routes.rb
UserTimeTracking::Application.routes.draw do
  get '/users/analytic' , to: 'users#analytic'
  get '/users/statistic', to: 'users#statistic' 
  post 'users/login'
  
  resources :users
  

  root 'users#index'
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	include Avg
	has_many :user_times , dependent: :destroy
	validates :name , :uniqueness=> true , 
					  :presence=> true ,
    				  length: { in: 6..15 }
    validates_format_of :name,  :with => /\A[a-zA-Z0-9]+[^\W]\z/
    
end

app/models/user_time.rb
class UserTime < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    
    time_range=Time.now.midnight..Time.now.end_of_day
    @usertimes=UserTime.where(:arrival_time=>time_range)
    @u=@usertimes.map{|e| e.user_id}
    @users=User.find(@u)
    #@users = @users.page(params[:page]).per(5)
    # @users = User.map{|e|e.user_times.where(:arrival_time=>time_range)}.paginate :page=>params[:page], :per_page => 10
    # @products = Product.order("name").page(params[:page]).per(5)

  end

  # GET /users/1
  # GET /users/1.json
  def show
      
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def login
    if @user=User.find_by_name(params[:name])
      
      session[:user_id]=@user.id
      @user_time=UserTime.new
      @user_time=@user.user_times.create(:arrival_time=>Time.now,:user_id=>@user.id)
      if @user.role == true
          render layout: "admin"
      else
        redirect_to user_path(@user) 
      end
    else
      redirect_to users_url , :notice=>"Invalid User"
    end
  end
 

  def analytic
      @users=User.all
      time_range=Time.now.midnight..Time.now.end_of_day
      @usertimes=UserTime.where(:arrival_time=>time_range)
      if @usertimes.present? 

        @u=@usertimes.map{|e| e.arrival_time.localtime}
        @a=@u.map{|e| e.strftime("%H:%M")}
      else
        redirect_to "/users", :notice => "no user logged in yet"
      end
  end

  def statistic
    
    @users=User.all
    @user_times=UserTime.where(arrival_time: (DateTime.now.beginning_of_month..DateTime.now.end_of_month))
    
  end
    
  
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
   
    respond_to do |format|
      if @user.save
        format.html { render layout: 'admin', notice: 'User was successfully created.' }
        format.json { render action: 'index', status: :created, location: users_path }
        # @user_time=UserTime.new
        # @user_time=@user.user_times.create(:arrival_time=>Time.now,:user_id=>@user.id)
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { render layout: "admin" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
Admin

<p id="notice"><%= notice %></p>
<%= link_to "My Show Page" , user_path(@user.id) %><br><br>
<%= link_to "Add New User" , new_user_path %><br><br>

<table border="1">
  <thead>
    <tr>
      <th>User Name</th>
      <th>User Id</th>
      <th>Delete Button</th>
    </tr>
  </thead> 

  <tbody>
   		 <% @users=User.all %>
   		 <%@users.sort_by!{|e| e.name.downcase}%>
   		 <% @users.each  do |user| %>
      <tr>
          <td><%= user.name %></td>
          <td><%= user.id %></td>
          <td><%= button_to "Delete" , {:action => "destroy" ,:id => user.id}, method: 'delete' %></td>
       </tr>
     <%end%>
  
  </tbody> 
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<center><h1><font color="#800000">Welcome To User Time Tracking System!</font></h1><br></center>
<head>
  <title>UserTimeTracking</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#FAF0FF;">

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , :maxlength => 15 %>
  </div>
  <div class="field">
    <%= f.hidden_field :role, :value => 0 %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/analytic.html.erb
<p id="notice"><%= notice %></p>
<h2>
<%=  "The Average Time of all Users for #{Date.today} is #{@users.first.average_time(@a)}"%>
</h2>

app/views/users/create.html.erb
create

app/views/users/destroy.html.erb
destroy

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1><p id="notice"><%= notice %></p></h1>
<div align="left">
 <h2><%= link_to 'Analytics' , users_analytic_path %></h2>
 <h2><%= link_to 'Satistics' , users_statistic_path %></h2>
</div> 
<center>
<fieldset>
  <h3><b> Please Sign in</b><br>
  <br>
    <%= form_tag(:action=>'login') do %>

      <b><%= label_tag(:name,    "Name:  ") %></b>
      <%= text_field_tag(:name) %>
    <br>
    <br>
      <%= submit_tag 'login'%>
    <%end %></h3>
 </fieldset>
<br>
<br>
 <fieldset>
<h3>Users currently logged in</h3>
<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>User Login Time</th>
      <th>Role</th>
    
    </tr>
  </thead> 

  <tbody>
     
    <% @users.sort_by!{|e| e.name.downcase}%>
    <% @users.each do |user| %>
   
      <tr>
        <font color="green"><td><%= link_to "#{user.name}" , user_path(user.id)%></td></font>

        <td><%= user.user_times.last.arrival_time.localtime %></td>
        <td><% if user.role == true %>
                <%= "Admin" %>
            <% else %>  
                 <%= "Employee" %>
             <%end%>
        </td>
       
      </tr>
    <% end %>
  </tbody> 
</table>
 </fieldset>

  
 
</center>
<%#= will_paginate @user %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% a=@user.user_times.last.arrival_time.localtime%>
<% if a.strftime("%H:%M:%S :%z") > ("10:00:00 +0530") %>
	<font color="red" , size="5px" ><%="You Are Late!!!"%></font>
<% else %>
	<font color="green" , size="5px"><%="You Arrived On Time!!"%></font>
<%end%>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong> 
  <% if @user.role == true %>
   		<%= "Admin " %>
  <% else %>	
  		<%= "Employee " %>
  <%end%>
</p>

<p>
<strong>Arrival Time : </strong>
<%= @user.user_times.last.arrival_time.localtime %>

</p>
<br>
<br>

<fieldset>
<h3><%="#{@user.name}'s arrival time:"%></h3>
<table border="1">
  <thead>
    <tr>
      <th>User Login Time</th>
    </tr>
  </thead> 

  <tbody>
   
      <tr>
          <% @user.user_times.map do |e| %>
          <td><%=e.arrival_time.localtime%></td>
          
       </tr>
     <%end%>
  
  </tbody> 
</table>
 </fieldset>
 <br><br>
  <% a= @user.user_times.map{|e|e.arrival_time.localtime.strftime("%H:%M")}%>
 <%= "The average arrival time for #{@user.name} is  #{@user.average_time(a)}"%>
 <br>
 <br>
<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'logout', users_path %>

app/views/users/statistic.html.erb
Statistic
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>No. of Late Arrivals</th>
      <th>Average Arrival Time</th>
     
    </tr>
  </thead>

  <tbody>
  	<%@users.sort_by!{|e| e.name.downcase}%>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <% count=0 %>
        <% a=user.user_times.map{|e| e.arrival_time.localtime.strftime("%H:%M:%S :%z")}%>
		<% for i in 0..a.length-1 %>
		<% if a[i] > ("10:00:00 +0530") %>
			<% count=count+1 %>
		<%end%>
		<%end%>
        <% c=Array.new %><% c<<count%>
        <td><%= "#{count}" %></td>
        
        <td><%= number_with_precision(user.average_time(a), :precision => 2)%></td>
       
      </tr>
    <% end %>
  </tbody>                 
</table>

<br>